language: php

php:
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache/files
    - vendor

before_script:
  - composer install

script:
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)
